/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddDatasource: typeof import('./src/components/AddDatasource.vue')['default']
    AnnotateTables: typeof import('./src/components/AnnotateTables.vue')['default']
    ConnectAirbyte: typeof import('./src/components/ConnectAirbyte.vue')['default']
    ConnectMotherduck: typeof import('./src/components/ConnectMotherduck.vue')['default']
    ConnectRepository: typeof import('./src/components/ConnectRepository.vue')['default']
    DynamicFields: typeof import('./src/components/DynamicFields.vue')['default']
    ImportWizard: typeof import('./src/components/ImportWizard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
