/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddGithubSource: typeof import('./src/components/AddGithubSource.vue')['default']
    AddPostgresSource: typeof import('./src/components/AddPostgresSource.vue')['default']
    AnnotateTables: typeof import('./src/components/AnnotateTables.vue')['default']
    ConnectAirbyte: typeof import('./src/components/ConnectAirbyte.vue')['default']
    ConnectMotherduck: typeof import('./src/components/ConnectMotherduck.vue')['default']
    ConnectRepository: typeof import('./src/components/ConnectRepository.vue')['default']
    DynamicFields: typeof import('./src/components/DynamicFields.vue')['default']
    FetchSchema: typeof import('./src/components/FetchSchema.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    ManageInfoSources: typeof import('./src/components/ManageInfoSources.vue')['default']
    ManageSchema: typeof import('./src/components/ManageSchema.vue')['default']
    ManageSources: typeof import('./src/components/ManageSources.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WorkspaceView: typeof import('./src/components/WorkspaceView.vue')['default']
  }
}
